apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guiss0/html-app
  template:
    metadata:
      labels:
        app: guiss0/html-app
    spec:
      containers:
        - name: html-app
          image: guiss0/html-app:latest  # Imagen de Docker Hub desde los secretos de GitHub Actions
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ${{ secrets.DOCKER_REGISTRY_SECRET }}
---
apiVersion: v1
kind: Service
metadata:
  name: html-app
spec:
  selector:
    app: guiss0/html-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort
