name: Build, Push and Deploy to Kubernetes

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: html-app
  REGISTRY: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build-push-deploy:
    runs-on: self-hosted  # Especificamos que debe usar el runner local

    steps:
      - name: Login to Docker Hub
        run: |
              docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
              
      - name: Build and Push Docker Image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:latest .
          docker push $REGISTRY/$IMAGE_NAME:latest

      - name: Setup kubectl
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl version --client

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
